[package]
name = "big-rust-preschool"
version = "0.1.0"
authors = ["saglam"]
edition = "2018"

[lib]
name = "molecules"
path = "molecules.rs"

[[bench]]
name = "bench"
path = "bench.rs"

[dependencies]
order-stat = "0.1"
atoi = "0.3.2"